services:
  - type: web
    name: cybersecurity-tools-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: AUTH0_DOMAIN
        sync: false
      - key: API_AUDIENCE
        sync: false
      - key: API_IDENTIFIER
        sync: false
      - key: AUTH0_CLIENT_ID
        sync: false
      - key: AUTH0_CLIENT_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cybersecurity-tools-db
          property: connectionString

databases:
  - name: cybersecurity-tools-db
    databaseName: cybersecurity_tools
    user: cybersecurity_tools_user
    plan: free